GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.testtable TO ssbd03mok;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.testtable2 TO ssbd03mop;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.parking TO ssbd03mop;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.sector TO ssbd03mop;