package pl.lodz.p.it.ssbd2024.ssbd03.commons.dto.mop.reservationDTO;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ParkingEventOutputDTO {

    @Schema(description = "UUID identifier of the parking event linked with the reservation", example = "c276cb93-5cfe-4bf5-9998-ecdeee8ba06b", requiredMode = Schema.RequiredMode.REQUIRED)
    private UUID id;

    @Schema(description = "Type of the parking event", example = "ENTRY", requiredMode = Schema.RequiredMode.REQUIRED)
    private String type;

    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @Schema(description = "Date and time, which the parking event took place at", example = "YYYY-MM-dd HH:mm", requiredMode = Schema.RequiredMode.REQUIRED)
    private LocalDateTime date;

    @Schema(description = "Login of the user, who the parking event was generated by.", example = "jerzybem", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String createdBy;
}
